### ISSUE TITLE
Recipient list wanted from /Center/DeltaMessage/Sent

### ISSUE THREAD

**Issue by vhsoft-ferryto** [VHSoft/VHSmartNext#143]
Need recipients list, in order to associate message to conversations. (saving them during send won’t do in case of reinstall)

**Comment by vhsoft-danielpoon** [comment]
I suggest this api should provide a full list of recipient including "message state" and "message recipient state".

**Comment by vhsoft-ferryto** [comment]
This issue fixed with branch #165
