### ISSUE TITLE
inspect ContractMembership.Add(ContractMember) bug

### ISSUE THREAD

**Issue by vhsoft-ferryto** [VHSoft/VHSmartNext#36]

**Comment by vhsoft-ferryto** [comment]
still need to investigate

**Comment by vhsoft-hclaw** [comment]
The following are the places that have used Children Lazy Loading:
Controller | Method | line # | Lazy loading (Children)
------------ | ------------- | ------------- | -------------
ApplicationRoleController | GetApplicationRoles | 461 | CorporateModuleRole.Members
ContractController | DeleteContract | 314 | Contract.ContractMembers
ContractController | DeleteContract | 317 | Contract.Sites
ContractController | DeleteContract | 320 | Contract.SiteLevelLabel
ContractController | DeleteContract | 323 | Contract.ContractGroup
GroupController | GetGroups | 237 | ContractGroup.ContractGroupMembers
MessageController | GetGroupMembers | 1346 | ContractGroup.ContractGroupMembers
RoleFunctionController | GetByUserId | 51 | CorporateModuleRoleMembership.Role.InternalRole.RoleFunctions
SiteController | GetByUserId | 49,67 | ContractMembership.Contract.Sites

**Comment by vhsoft-ferryto** [comment]
One to many relationships should able to add without error now.
