### ISSUE TITLE
Property 'Country' not found on entity Corporate

### ISSUE THREAD

**Issue by vhsoft-ferryto** [VHSoft/VHSmartNext#63]
When saving modifications on Corporate entity, InvalidOperationException throw at SaveChanges() that property 'Country' cannot be found.

**Comment by vhsoft-hclaw** [comment]
the error is:
The property 'Country' on entity type 'Corporate' could not be found. Ensure that the property exists and has been included in the model.
at line 73 in VHSmartDbContext

**Comment by vhsoft-ferryto** [comment]
Already fixed in commit #70
