### ISSUE TITLE
Cannot directly access Parent Entity

### ISSUE THREAD

**Issue by vhsoft-hclaw** [VHSoft/VHSmartNext#67]
When accessing the parent entity to retrieve parent's data through 
`<Entity>.<ParentEntity>.<ParentProperty>`
the parent entity is null and a NullReferenceException is catched.

This only occurs when the entity is already retrieved out of the DBSet (not in DBSet/IQueryable/IEnumerable).

For example in method 'GetMessageDetail' in Message Controller (line 581), `recipient.Mesage` is null and causing the NullReferenceException at run-time.

but if it is still in IQueryable/DBSet/IEnumerable, the parent entity is not null.
e.g. in method 'GetInboxMessages' in MessageController (line 478), `mr.Message` is not null.

**Comment by vhsoft-ferryto** [comment]
This can be fixed by using .Include() and .ThenInclude() syntax from Microsoft.EntityFrameworkCore namespace.
